version: "1"
services:
    dbase:    
        # image: db_epam
        build: .\bd\
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: "epam_pass"
        ports:
            - "3306:3306"
        networks:
            - webnet       
    web:
        build: .
        # image: web_epam
        ports:
            - "8080:8080"
        networks:
            - webnet    
networks:
    webnet: